// Generated by CoffeeScript 1.9.1
(function() {
  var BelongsToProperty, HasManyProperty, ModelRegistry, ModelRegistryProperty, RelationshipProperty, StormModel, StormObject, StormRegistry, assert,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  StormObject = require('./object');

  assert = require('assert');

  RelationshipProperty = (function(superClass) {
    extend(RelationshipProperty, superClass);

    RelationshipProperty.set({
      storm: 'relation'
    });

    RelationshipProperty.prototype.kind = null;

    function RelationshipProperty(model1, opts, obj) {
      var ref, type;
      this.model = model1;
      if (opts == null) {
        opts = {};
      }
      assert(typeof ((ref = this.model) != null ? ref.constructor : void 0) === 'function', "cannot register a new relationship without proper model class");
      assert(obj instanceof StormModel, "cannot register a new relationship without containing obj defined");
      type = (function() {
        switch (this.kind) {
          case 'belongsTo':
            return 'string';
          case 'hasMany':
            return 'array';
        }
      }).call(this);
      if (this.kind === 'hasMany') {
        opts.unique = true;
      }
      RelationshipProperty.__super__.constructor.call(this, type, opts, obj);
    }

    return RelationshipProperty;

  })(StormObject.Property);

  BelongsToProperty = (function(superClass) {
    extend(BelongsToProperty, superClass);

    function BelongsToProperty() {
      return BelongsToProperty.__super__.constructor.apply(this, arguments);
    }

    BelongsToProperty.set({
      storm: 'belongsTo'
    });

    BelongsToProperty.prototype.kind = 'belongsTo';

    BelongsToProperty.prototype.get = function() {
      return this.model.prototype.fetch(BelongsToProperty.__super__.get.apply(this, arguments));
    };

    BelongsToProperty.prototype.validate = function(value) {
      if (value == null) {
        value = this.value;
      }
      return (BelongsToProperty.__super__.validate.call(this, value)) === true && ((value == null) || this.model.prototype.fetch(value instanceof this.model));
    };

    BelongsToProperty.prototype.normalize = function(value) {
      var record;
      switch (false) {
        case !(value == null):
          return void 0;
        case !(value instanceof this.model):
          return value.get('id');
        case typeof value !== 'string':
          return value;
        case typeof value !== 'number':
          return "" + value;
        case !(value instanceof Array):
          return void 0;
        case !(value instanceof Object):
          record = new this.model(value);
          this.obj.bind(record);
          return this.normalize(record);
        default:
          return void 0;
      }
    };

    BelongsToProperty.prototype.serialize = function(format) {
      if (format == null) {
        format = 'json';
      }
      if (this.opts.embedded === true) {
        return this.get().serialize(format);
      } else {
        return BelongsToProperty.__super__.serialize.apply(this, arguments);
      }
    };

    return BelongsToProperty;

  })(RelationshipProperty);

  HasManyProperty = (function(superClass) {
    extend(HasManyProperty, superClass);

    function HasManyProperty() {
      return HasManyProperty.__super__.constructor.apply(this, arguments);
    }

    HasManyProperty.set({
      storm: 'hasMany'
    });

    HasManyProperty.prototype.kind = 'hasMany';

    HasManyProperty.prototype.get = function() {
      return (HasManyProperty.__super__.get.apply(this, arguments).map((function(_this) {
        return function(e) {
          return _this.model.prototype.fetch(e);
        };
      })(this))).filter(function(e) {
        return e != null;
      });
    };

    HasManyProperty.prototype.push = function(value) {
      var list;
      list = this.get();
      list.push(value);
      return this.set(list);
    };

    HasManyProperty.prototype.validate = function(value) {
      if (value == null) {
        value = this.value;
      }
      return (HasManyProperty.__super__.validate.call(this, value)) === true && value.every((function(_this) {
        return function(e) {
          return (_this.model.prototype.fetch(e)) instanceof _this.model;
        };
      })(this));
    };

    HasManyProperty.prototype.normalize = function(value) {
      value = HasManyProperty.__super__.normalize.call(this, value);
      return HasManyProperty.__super__.normalize.call(this, (function() {
        switch (false) {
          case !(value instanceof Array):
            return (value.filter(function(e) {
              return e != null;
            })).map((function(_this) {
              return function(e) {
                return BelongsToProperty.prototype.normalize.call(_this, e);
              };
            })(this));
          default:
            return void 0;
        }
      }).call(this));
    };

    HasManyProperty.prototype.serialize = function(format) {
      if (format == null) {
        format = 'json';
      }
      if (this.opts.embedded === true) {
        return this.get().map(function(e) {
          return e.serialize(format);
        });
      } else {
        return HasManyProperty.__super__.serialize.apply(this, arguments);
      }
    };

    return HasManyProperty;

  })(RelationshipProperty);

  StormRegistry = require('./registry');

  ModelRegistryProperty = (function(superClass) {
    extend(ModelRegistryProperty, superClass);

    function ModelRegistryProperty(model1, opts, obj) {
      this.model = model1;
      ModelRegistryProperty.__super__.constructor.call(this, 'object', opts, obj);
    }

    ModelRegistryProperty.prototype.match = function(query, keys) {
      var k, ref, results, v;
      if (keys == null) {
        keys = false;
      }
      switch (false) {
        case !(query instanceof Array):
          return ModelRegistryProperty.__super__.match.apply(this, arguments);
        case !(query instanceof Object):
          ref = this.get();
          results = [];
          for (k in ref) {
            v = ref[k];
            if (v.match(query)) {
              if (keys) {
                results.push(k);
              } else {
                results.push(v);
              }
            }
          }
          return results;
          break;
        default:
          return ModelRegistryProperty.__super__.match.apply(this, arguments);
      }
    };

    ModelRegistryProperty.prototype.serialize = function(format) {
      if (format == null) {
        format = 'json';
      }
      return {
        ids: Object.keys(this.value),
        numRecords: Object.keys(this.value).length
      };
    };

    return ModelRegistryProperty;

  })(StormRegistry.Property);

  ModelRegistry = (function(superClass) {
    extend(ModelRegistry, superClass);

    function ModelRegistry() {
      return ModelRegistry.__super__.constructor.apply(this, arguments);
    }

    ModelRegistry.Property = ModelRegistryProperty;

    ModelRegistry.prototype.register = function(model, opts) {
      return ModelRegistry.__super__.register.call(this, model.meta.name, new ModelRegistryProperty(model, opts, this));
    };

    ModelRegistry.prototype.add = function() {
      var i, len, obj, record, records;
      records = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      obj = {};
      for (i = 0, len = records.length; i < len; i++) {
        record = records[i];
        if (record instanceof StormModel) {
          obj[record.get('id')] = record;
        }
      }
      return ModelRegistry.__super__.add.call(this, record.constructor.meta.name, obj);
    };

    ModelRegistry.prototype.remove = function() {
      var query, record, records;
      records = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      query = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = records.length; i < len; i++) {
          record = records[i];
          if (record instanceof StormModel) {
            results.push(record.get('id'));
          }
        }
        return results;
      })();
      return ModelRegistry.__super__.remove.call(this, record.constructor.meta.name, query);
    };

    ModelRegistry.prototype.contains = function(key) {
      return this.getProperty(key);
    };

    return ModelRegistry;

  })(StormRegistry);

  StormModel = (function(superClass) {
    var Promise;

    extend(StormModel, superClass);

    StormModel.set({
      storm: 'model'
    });

    StormModel.belongsTo = function(model, opts) {
      return (function(superClass1) {
        extend(_Class, superClass1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.set({
          type: model,
          opts: opts
        });

        return _Class;

      })(BelongsToProperty);
    };

    StormModel.hasMany = function(model, opts) {
      return (function(superClass1) {
        extend(_Class, superClass1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.set({
          type: model,
          opts: opts
        });

        return _Class;

      })(HasManyProperty);
    };

    StormModel.action = function(func, opts) {
      return (function(superClass1) {
        extend(_Class, superClass1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.set({
          type: func,
          opts: opts
        });

        return _Class;

      })(ActionProperty);
    };

    StormModel.RelationshipProperty = RelationshipProperty;

    StormModel.HasManyProperty = HasManyProperty;

    StormModel.BelongsToProperty = BelongsToProperty;

    StormModel.prototype.id = StormModel.attr('string', {
      "private": true,
      defaultValue: function() {
        return (require('node-uuid')).v4();
      }
    });

    StormModel.prototype.createdOn = StormModel.attr('date', {
      "private": true,
      defaultValue: function() {
        return new Date;
      }
    });

    StormModel.prototype.modifiedOn = StormModel.attr('date', {
      "private": true,
      defaultValue: function() {
        return new Date;
      }
    });

    StormModel.prototype.accessedOn = StormModel.attr('date', {
      "private": true,
      defaultValue: function() {
        return new Date;
      }
    });

    StormModel.prototype._bindings = StormModel.hasMany(StormModel, {
      "private": true
    });

    StormModel.prototype._models = new ModelRegistry;

    function StormModel() {
      StormModel.__super__.constructor.apply(this, arguments);
      this._models.register(this.constructor);
      this._models.add(this);
    }

    StormModel.prototype.get = function() {
      this.set('accessedOn', new Date);
      return StormModel.__super__.get.apply(this, arguments);
    };

    StormModel.prototype.fetch = function(id) {
      return this._models.find(this.constructor.meta.name, id);
    };

    StormModel.prototype.getRelationships = function(kind) {
      return this.everyProperty(function(key) {
        if (this instanceof RelationshipProperty) {
          return this;
        }
      }).filter(function(x) {
        return (x != null) && ((kind == null) || kind === x.kind);
      });
    };


    /**
     * `bind` subjugates passed in records to be bound to the lifespan of
     * the current model record.
    #
     * When this current model record is destroyed, all bound dependents
     * will also be destroyed.
     */

    StormModel.prototype.bind = function() {
      var i, len, record, records, results;
      records = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      results = [];
      for (i = 0, len = records.length; i < len; i++) {
        record = records[i];
        if (!((record != null) && record instanceof StormModel)) {
          continue;
        }
        results.push((this.getProperty('_bindings')).push(record.save()));
      }
      return results;
    };

    StormModel.prototype.match = function(query) {
      var k, ref, v, x;
      for (k in query) {
        v = query[k];
        x = (ref = this.getProperty(k)) != null ? ref.normalize(this.get(k)) : void 0;
        if (typeof x === 'boolean' && typeof v === 'string') {
          x = "" + x;
        }
        if (x !== v) {
          return false;
        }
      }
      return true;
    };

    StormModel.prototype.save = function() {
      var isValid;
      isValid = this.validate();
      if (isValid.length === 0) {
        if (this.isDirty()) {
          this.set('modifiedOn', new Date);
        }
        this.clearDirty();
        this._models.add(this);
        return this;
      } else {
        return null;
      }
    };

    StormModel.prototype.destroy = function() {
      var i, len, record, ref;
      ref = this.get('_bindings');
      for (i = 0, len = ref.length; i < len; i++) {
        record = ref[i];
        record.destroy();
      }
      return this._models.remove(this);
    };

    Promise = require('promise');

    StormModel.prototype.invoke = function() {
      var action, args;
      action = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return new Promise((function(_this) {
        return function(resolve, reject) {
          var err, ref;
          try {
            if (!(action instanceof Function)) {
              action = (ref = _this.getProperty(action)) != null ? ref.exec : void 0;
            }
            return resolve(action != null ? action.apply(_this, args) : void 0);
          } catch (_error) {
            err = _error;
            return reject(err);
          }
        };
      })(this));
    };

    return StormModel;

  })(StormObject);

  module.exports = StormModel;

}).call(this);
