// Generated by CoffeeScript 1.9.1
(function() {
  var EventEmitter, RegistryProperty, StormObject, StormRegistry,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  StormObject = require('./object');


  /**
   * `RegistryProperty` is a hash map collection (holding value of type Object)
   */

  RegistryProperty = (function(superClass) {
    extend(RegistryProperty, superClass);

    function RegistryProperty(type, opts, obj) {
      RegistryProperty.__super__.constructor.call(this, 'object', opts, obj);
      this.set({});
    }

    RegistryProperty.prototype.match = function(query, keys) {
      var hit, item, k, key, map, match, results, results1, results2, v;
      if (keys == null) {
        keys = false;
      }
      map = this.get();
      switch (false) {
        case !(query instanceof Array):
          results1 = [];
          for (k in map) {
            v = map[k];
            if (indexOf.call(query, k) >= 0) {
              if (keys) {
                results1.push(k);
              } else {
                results1.push(v);
              }
            }
          }
          return results1;
          break;
        case !(query instanceof Object):
          if (!keys) {
            return ((function() {
              var results2;
              results2 = [];
              for (k in map) {
                v = map[k];
                results2.push(v);
              }
              return results2;
            })()).where(query);
          } else {
            results = [];
            hit = Object.keys(query).length;
            for (key in map) {
              item = map[key];
              match = 0;
              for (k in query) {
                v = query[k];
                if (item[k] === v) {
                  match += 1;
                }
              }
              if (match === hit) {
                results.push(key);
              }
            }
            return results;
          }
          break;
        case query == null:
          if (!keys) {
            return map[query];
          } else {
            if (map.hasOwnProperty(query)) {
              return query;
            } else {
              return null;
            }
          }
          break;
        case !keys:
          return Object.keys(map);
        default:
          results2 = [];
          for (k in map) {
            v = map[k];
            results2.push(v);
          }
          return results2;
      }
    };

    RegistryProperty.prototype.merge = function(obj) {
      var k, results1, v;
      results1 = [];
      for (k in obj) {
        v = obj[k];
        results1.push(this.value[k] = v);
      }
      return results1;
    };

    RegistryProperty.prototype.remove = function(query) {
      var i, key, keys, len, results1;
      keys = this.match(query, true);
      switch (false) {
        case !(keys instanceof Array):
          results1 = [];
          for (i = 0, len = keys.length; i < len; i++) {
            key = keys[i];
            results1.push(delete this.value[key]);
          }
          return results1;
          break;
        case keys == null:
          return delete this.value[keys];
      }
    };

    return RegistryProperty;

  })(StormObject.Property);

  EventEmitter = require('events').EventEmitter;


  /**
   * StormRegistry
  #
   * map of key: RegistryProperty
  #
   * primary methods:
  #
   * register()
   * find()
   * update()
   * remove()
   */

  StormRegistry = (function(superClass) {
    extend(StormRegistry, superClass);

    function StormRegistry() {
      return StormRegistry.__super__.constructor.apply(this, arguments);
    }

    StormRegistry.set({
      storm: 'registry'
    });

    StormRegistry.include(EventEmitter);

    StormRegistry.Property = RegistryProperty;

    StormRegistry.prototype.register = function(key, property) {
      return this.addProperty(key, property);
    };

    StormRegistry.prototype.keys = function() {
      return StormRegistry.__super__.keys.apply(this, arguments).filter((function(_this) {
        return function(key) {
          return (_this.getProperty(key)) instanceof RegistryProperty;
        };
      })(this));
    };

    StormRegistry.prototype.find = function(key, query) {
      var ref;
      return (ref = this.getProperty(key)) != null ? ref.match(query) : void 0;
    };

    StormRegistry.prototype.add = function(key, value) {
      var ref;
      return (ref = this.getProperty(key)) != null ? ref.merge(value) : void 0;
    };

    StormRegistry.prototype.remove = function(key, query) {
      var ref;
      return (ref = this.getProperty(key)) != null ? ref.remove(query) : void 0;
    };

    return StormRegistry;

  })(StormObject);

  module.exports = StormRegistry;

}).call(this);
